services:
  - type: web
    name: ytmp3-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: MAX_CONCURRENT_DOWNLOADS
        value: 1
      - key: CLEANUP_AGE_SECONDS
        value: 1800
